"""autodetect_missing_tables

Revision ID: 4e49118f6e51
Revises: a9b8c7d6e5f4
Create Date: 2026-06-04 10:39:32.095184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e49118f6e51'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_booking_timeline_booking_id'), 'booking_timeline', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_bookings_hotel_id_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id_status'), table_name='bookings')
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.drop_column('bookings', 'show_in_social_proof')
    op.drop_index(op.f('ix_channel_room_mappings_local_room_id'), table_name='channel_room_mappings')
    op.create_index(op.f('ix_competitor_rates_check_in_date'), 'competitor_rates', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_competitor_rates_is_sold_out'), 'competitor_rates', ['is_sold_out'], unique=False)
    op.alter_column('hotels', 'feature_google_ads',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_hotels_chain_id'), 'hotels', ['chain_id'], unique=False)
    op.drop_constraint(op.f('hotels_chain_id_fkey'), 'hotels', type_='foreignkey')
    op.create_foreign_key(None, 'hotels', 'chains', ['chain_id'], ['id'])
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_promo_codes_hotel_id_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_index(op.f('ix_promo_codes_hotel_id'), 'promo_codes', ['hotel_id'], unique=False)
    op.drop_index(op.f('ix_rate_plans_hotel_id_is_active'), table_name='rate_plans')
    op.drop_index(op.f('ix_room_amenity_links_amenity_id'), table_name='room_amenity_links')
    op.create_index(op.f('ix_room_rates_hotel_id'), 'room_rates', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_rates_rate_plan_id'), 'room_rates', ['rate_plan_id'], unique=False)
    op.drop_index(op.f('ix_room_types_hotel_id_is_active'), table_name='room_types')
    op.create_index(op.f('ix_subscriptions_hotel_id'), 'subscriptions', ['hotel_id'], unique=False)
    op.drop_index(op.f('ix_user_hotel_links_hotel_id'), table_name='user_hotel_links')
    op.create_index(op.f('ix_users_chain_id'), 'users', ['chain_id'], unique=False)
    op.drop_constraint(op.f('users_chain_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'chains', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_chain_id_fkey'), 'users', 'chains', ['chain_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_chain_id'), table_name='users')
    op.create_index(op.f('ix_user_hotel_links_hotel_id'), 'user_hotel_links', ['hotel_id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_hotel_id'), table_name='subscriptions')
    op.create_index(op.f('ix_room_types_hotel_id_is_active'), 'room_types', ['hotel_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_room_rates_rate_plan_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_hotel_id'), table_name='room_rates')
    op.create_index(op.f('ix_room_amenity_links_amenity_id'), 'room_amenity_links', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_rate_plans_hotel_id_is_active'), 'rate_plans', ['hotel_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_promo_codes_hotel_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_hotel_id_code'), 'promo_codes', ['hotel_id', 'code'], unique=True)
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.create_foreign_key(op.f('hotels_chain_id_fkey'), 'hotels', 'chains', ['chain_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_hotels_chain_id'), table_name='hotels')
    op.alter_column('hotels', 'feature_google_ads',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_competitor_rates_is_sold_out'), table_name='competitor_rates')
    op.drop_index(op.f('ix_competitor_rates_check_in_date'), table_name='competitor_rates')
    op.create_index(op.f('ix_channel_room_mappings_local_room_id'), 'channel_room_mappings', ['local_room_id'], unique=False)
    op.add_column('bookings', sa.Column('show_in_social_proof', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.create_index(op.f('ix_bookings_hotel_id_status'), 'bookings', ['hotel_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_id_created_at'), 'bookings', ['hotel_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_booking_timeline_booking_id'), table_name='booking_timeline')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    # ### end Alembic commands ###
