"""add_google_business_oauth_tokens

Revision ID: e0b7eb25bb68
Revises: a1b2c3d4e5f6
Create Date: 2026-05-29 15:17:24.060778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0b7eb25bb68'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('amenities_hotel_id_fkey'), 'amenities', type_='foreignkey')
    op.create_foreign_key(None, 'amenities', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('idx_analytics_events_session_id'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.drop_constraint(op.f('analytics_events_session_id_fkey'), 'analytics_events', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_events', 'analytics_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('idx_analytics_sessions_hotel_id'), table_name='analytics_sessions')
    op.drop_constraint(op.f('analytics_sessions_hotel_id_fkey'), 'analytics_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_sessions', 'hotels', ['hotel_id'], ['id'])
    op.create_index(op.f('ix_booking_timeline_booking_id'), 'booking_timeline', ['booking_id'], unique=False)
    op.drop_constraint(op.f('booking_timeline_booking_id_fkey'), 'booking_timeline', type_='foreignkey')
    op.create_foreign_key(None, 'booking_timeline', 'bookings', ['booking_id'], ['id'])
    op.alter_column('bookings', 'cancellation_fee',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'refund_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'subtotal_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'tax_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_index(op.f('idx_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_hotel_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.drop_constraint(op.f('bookings_hotel_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'hotels', ['hotel_id'], ['id'])
    op.drop_constraint(op.f('channel_manager_settings_hotel_id_fkey'), 'channel_manager_settings', type_='foreignkey')
    op.create_foreign_key(None, 'channel_manager_settings', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('idx_channel_room_mappings_local_room_id'), table_name='channel_room_mappings')
    op.create_index(op.f('ix_competitor_rates_check_in_date'), 'competitor_rates', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_competitor_rates_is_sold_out'), 'competitor_rates', ['is_sold_out'], unique=False)
    op.drop_constraint(op.f('competitor_rates_competitor_id_fkey'), 'competitor_rates', type_='foreignkey')
    op.create_foreign_key(None, 'competitor_rates', 'competitors', ['competitor_id'], ['id'])
    op.drop_constraint(op.f('competitors_hotel_id_fkey'), 'competitors', type_='foreignkey')
    op.create_foreign_key(None, 'competitors', 'hotels', ['hotel_id'], ['id'])
    op.drop_constraint(op.f('guests_hotel_id_fkey'), 'guests', type_='foreignkey')
    op.create_foreign_key(None, 'guests', 'hotels', ['hotel_id'], ['id'])
    op.alter_column('hotels', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('hotels', 'feature_new_booking',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_color_palette',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_custom_logo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_custom_widget',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_hotels_slug'), table_name='hotels')
    op.add_column('integration_settings', sa.Column('google_business_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('integration_settings', sa.Column('google_business_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('integration_settings', sa.Column('google_business_location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('integration_settings', sa.Column('google_business_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('integration_settings', 'widget_custom_css',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('integration_settings', 'widget_custom_js',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint(op.f('integration_settings_hotel_id_fkey'), 'integration_settings', type_='foreignkey')
    op.create_foreign_key(None, 'integration_settings', 'hotels', ['hotel_id'], ['id'])
    op.drop_constraint(op.f('leads_hotel_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'hotels', ['hotel_id'], ['id'])
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.drop_constraint(op.f('payments_hotel_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_booking_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'hotels', ['hotel_id'], ['id'])
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_index(op.f('ix_promo_codes_hotel_id'), 'promo_codes', ['hotel_id'], unique=False)
    op.drop_constraint(op.f('promo_codes_hotel_id_fkey'), 'promo_codes', type_='foreignkey')
    op.create_foreign_key(None, 'promo_codes', 'hotels', ['hotel_id'], ['id'])
    op.alter_column('rate_plans', 'is_package',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rate_plans', 'package_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('rate_plans_hotel_id_fkey'), 'rate_plans', type_='foreignkey')
    op.create_foreign_key(None, 'rate_plans', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('idx_room_amenity_links_amenity_id'), table_name='room_amenity_links')
    op.drop_constraint(op.f('room_amenity_links_amenity_id_fkey'), 'room_amenity_links', type_='foreignkey')
    op.drop_constraint(op.f('room_amenity_links_room_id_fkey'), 'room_amenity_links', type_='foreignkey')
    op.create_foreign_key(None, 'room_amenity_links', 'amenities', ['amenity_id'], ['id'])
    op.create_foreign_key(None, 'room_amenity_links', 'room_types', ['room_id'], ['id'])
    op.drop_constraint(op.f('room_blocks_hotel_id_fkey'), 'room_blocks', type_='foreignkey')
    op.drop_constraint(op.f('room_blocks_room_type_id_fkey'), 'room_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'room_blocks', 'room_types', ['room_type_id'], ['id'])
    op.create_foreign_key(None, 'room_blocks', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('idx_room_rates_dates'), table_name='room_rates')
    op.drop_index(op.f('idx_room_rates_room_type_id'), table_name='room_rates')
    op.create_index(op.f('ix_room_rates_date_from'), 'room_rates', ['date_from'], unique=False)
    op.create_index(op.f('ix_room_rates_date_to'), 'room_rates', ['date_to'], unique=False)
    op.create_index(op.f('ix_room_rates_hotel_id'), 'room_rates', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_rates_rate_plan_id'), 'room_rates', ['rate_plan_id'], unique=False)
    op.drop_constraint(op.f('room_rates_room_type_id_fkey'), 'room_rates', type_='foreignkey')
    op.drop_constraint(op.f('room_rates_hotel_id_fkey'), 'room_rates', type_='foreignkey')
    op.create_foreign_key(None, 'room_rates', 'room_types', ['room_type_id'], ['id'])
    op.create_foreign_key(None, 'room_rates', 'hotels', ['hotel_id'], ['id'])
    op.alter_column('room_types', 'smoking_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('room_types', 'is_pet_friendly',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('room_types', 'cancellation_policy',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('room_types_hotel_id_fkey'), 'room_types', type_='foreignkey')
    op.create_foreign_key(None, 'room_types', 'hotels', ['hotel_id'], ['id'])
    op.create_index(op.f('ix_subscriptions_hotel_id'), 'subscriptions', ['hotel_id'], unique=False)
    op.drop_constraint(op.f('subscriptions_hotel_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('idx_user_hotel_links_hotel_id'), table_name='user_hotel_links')
    op.drop_index(op.f('idx_user_hotel_links_user_id'), table_name='user_hotel_links')
    op.drop_constraint(op.f('users_hotel_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_hotel_id_fkey'), 'users', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_user_hotel_links_user_id'), 'user_hotel_links', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_hotel_links_hotel_id'), 'user_hotel_links', ['hotel_id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_hotel_id_fkey'), 'subscriptions', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_hotel_id'), table_name='subscriptions')
    op.drop_constraint(None, 'room_types', type_='foreignkey')
    op.create_foreign_key(op.f('room_types_hotel_id_fkey'), 'room_types', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_types', 'cancellation_policy',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('room_types', 'is_pet_friendly',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('room_types', 'smoking_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'room_rates', type_='foreignkey')
    op.drop_constraint(None, 'room_rates', type_='foreignkey')
    op.create_foreign_key(op.f('room_rates_hotel_id_fkey'), 'room_rates', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_rates_room_type_id_fkey'), 'room_rates', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_room_rates_rate_plan_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_hotel_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_date_to'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_date_from'), table_name='room_rates')
    op.create_index(op.f('idx_room_rates_room_type_id'), 'room_rates', ['room_type_id'], unique=False)
    op.create_index(op.f('idx_room_rates_dates'), 'room_rates', ['date_from', 'date_to'], unique=False)
    op.drop_constraint(None, 'room_blocks', type_='foreignkey')
    op.drop_constraint(None, 'room_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('room_blocks_room_type_id_fkey'), 'room_blocks', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_blocks_hotel_id_fkey'), 'room_blocks', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'room_amenity_links', type_='foreignkey')
    op.drop_constraint(None, 'room_amenity_links', type_='foreignkey')
    op.create_foreign_key(op.f('room_amenity_links_room_id_fkey'), 'room_amenity_links', 'room_types', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_amenity_links_amenity_id_fkey'), 'room_amenity_links', 'amenities', ['amenity_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_room_amenity_links_amenity_id'), 'room_amenity_links', ['amenity_id'], unique=False)
    op.drop_constraint(None, 'rate_plans', type_='foreignkey')
    op.create_foreign_key(op.f('rate_plans_hotel_id_fkey'), 'rate_plans', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rate_plans', 'package_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('rate_plans', 'is_package',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'promo_codes', type_='foreignkey')
    op.create_foreign_key(op.f('promo_codes_hotel_id_fkey'), 'promo_codes', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_promo_codes_hotel_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_booking_id_fkey'), 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('payments_hotel_id_fkey'), 'payments', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_hotel_id_fkey'), 'leads', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'integration_settings', type_='foreignkey')
    op.create_foreign_key(op.f('integration_settings_hotel_id_fkey'), 'integration_settings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('integration_settings', 'widget_custom_js',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('integration_settings', 'widget_custom_css',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_column('integration_settings', 'google_business_account_id')
    op.drop_column('integration_settings', 'google_business_location_id')
    op.drop_column('integration_settings', 'google_business_refresh_token')
    op.drop_column('integration_settings', 'google_business_access_token')
    op.create_index(op.f('idx_hotels_slug'), 'hotels', ['slug'], unique=False)
    op.alter_column('hotels', 'photos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('hotels', 'feature_custom_widget',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_custom_logo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_color_palette',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_new_booking',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.create_foreign_key(op.f('guests_hotel_id_fkey'), 'guests', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'competitors', type_='foreignkey')
    op.create_foreign_key(op.f('competitors_hotel_id_fkey'), 'competitors', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'competitor_rates', type_='foreignkey')
    op.create_foreign_key(op.f('competitor_rates_competitor_id_fkey'), 'competitor_rates', 'competitors', ['competitor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_competitor_rates_is_sold_out'), table_name='competitor_rates')
    op.drop_index(op.f('ix_competitor_rates_check_in_date'), table_name='competitor_rates')
    op.create_index(op.f('idx_channel_room_mappings_local_room_id'), 'channel_room_mappings', ['local_room_id'], unique=False)
    op.drop_constraint(None, 'channel_manager_settings', type_='foreignkey')
    op.create_foreign_key(op.f('channel_manager_settings_hotel_id_fkey'), 'channel_manager_settings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_hotel_id_fkey'), 'bookings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.create_index(op.f('idx_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('idx_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('idx_bookings_created_at'), 'bookings', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'tax_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'subtotal_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'refund_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bookings', 'cancellation_fee',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(None, 'booking_timeline', type_='foreignkey')
    op.create_foreign_key(op.f('booking_timeline_booking_id_fkey'), 'booking_timeline', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_booking_timeline_booking_id'), table_name='booking_timeline')
    op.drop_constraint(None, 'analytics_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_sessions_hotel_id_fkey'), 'analytics_sessions', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_analytics_sessions_hotel_id'), 'analytics_sessions', ['hotel_id'], unique=False)
    op.drop_constraint(None, 'analytics_events', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_events_session_id_fkey'), 'analytics_events', 'analytics_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.create_index(op.f('idx_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.drop_constraint(None, 'amenities', type_='foreignkey')
    op.create_foreign_key(op.f('amenities_hotel_id_fkey'), 'amenities', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
