"""add_ai_keys

Revision ID: 0fbe11b44b0f
Revises: 044d2d8e76b2
Create Date: 2026-04-29 17:16:19.295351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0fbe11b44b0f'
down_revision: Union[str, Sequence[str], None] = '044d2d8e76b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amenities', 'scope',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'room'::text"))
    op.alter_column('amenities', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_bookings_dates'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_hotel_id'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_status'), table_name='bookings')
    op.drop_index(op.f('idx_competitor_rates_comp_id'), table_name='competitor_rates')
    op.drop_index(op.f('idx_competitor_rates_date'), table_name='competitor_rates')
    op.drop_index(op.f('idx_competitor_rates_sold_out'), table_name='competitor_rates')
    op.drop_index(op.f('idx_competitors_hotel_id'), table_name='competitors')
    op.add_column('hotels', sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hotels', sa.Column('ai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('hotels', 'feature_rate_shopper',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_ai_agent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_guest_bot',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('hotels', 'email')
    op.drop_column('hotels', 'banner_url')
    op.drop_column('hotels', 'phone')
    op.drop_column('hotels', 'metadata')
    op.drop_column('hotels', 'city')
    op.drop_column('hotels', 'stars')
    op.drop_column('hotels', 'location_data')
    op.drop_column('hotels', 'country')
    op.drop_column('hotels', 'is_verified')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.alter_column('rate_plans', 'price_adjustment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('rate_plans', 'min_los',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('rate_plans', 'advance_purchase_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rate_plans', 'inclusions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_room_amenity_links'), table_name='room_amenity_links')
    op.alter_column('room_rates', 'rate_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_rates_hotel_date'), table_name='room_rates')
    op.drop_index(op.f('idx_rates_room_type'), table_name='room_rates')
    op.alter_column('room_types', 'extra_person_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('room_types', 'extra_adult_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('room_types', 'extra_child_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('idx_room_types_hotel'), table_name='room_types')
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.create_index(op.f('idx_room_types_hotel'), 'room_types', ['hotel_id'], unique=False)
    op.alter_column('room_types', 'extra_child_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('room_types', 'extra_adult_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('room_types', 'extra_person_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('idx_rates_room_type'), 'room_rates', ['room_type_id'], unique=False)
    op.create_index(op.f('idx_rates_hotel_date'), 'room_rates', ['hotel_id', 'date_from', 'date_to'], unique=False)
    op.alter_column('room_rates', 'rate_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_room_amenity_links'), 'room_amenity_links', ['room_id', 'amenity_id'], unique=False)
    op.alter_column('rate_plans', 'inclusions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('rate_plans', 'advance_purchase_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rate_plans', 'min_los',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('rate_plans', 'price_adjustment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('hotels', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('stars', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('banner_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('hotels', 'feature_guest_bot',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_ai_agent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hotels', 'feature_rate_shopper',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('hotels', 'ai_api_key')
    op.drop_column('hotels', 'ai_provider')
    op.create_index(op.f('idx_competitors_hotel_id'), 'competitors', ['hotel_id'], unique=False)
    op.create_index(op.f('idx_competitor_rates_sold_out'), 'competitor_rates', ['is_sold_out'], unique=False)
    op.create_index(op.f('idx_competitor_rates_date'), 'competitor_rates', ['check_in_date'], unique=False)
    op.create_index(op.f('idx_competitor_rates_comp_id'), 'competitor_rates', ['competitor_id'], unique=False)
    op.create_index(op.f('idx_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('idx_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('idx_bookings_dates'), 'bookings', ['check_in', 'check_out'], unique=False)
    op.alter_column('amenities', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('amenities', 'scope',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'room'::text"))
    # ### end Alembic commands ###
