"""fresh_initial_schema

Revision ID: 20023f02b43d
Revises: 
Create Date: 2026-02-03 17:12:57.580578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20023f02b43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_review_hash'), table_name='review')
    op.drop_table('review')
    op.alter_column('integration_settings', 'widget_background_color',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'#FFFFFF'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integration_settings', 'widget_background_color',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'#FFFFFF'"))
    op.create_table('review',
    sa.Column('guest_name', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('review_text', sa.VARCHAR(), nullable=True),
    sa.Column('review_date', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('ai_reply_draft', sa.VARCHAR(), nullable=True),
    sa.Column('final_reply', sa.VARCHAR(), nullable=True),
    sa.Column('reply_date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hotel_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('review_hash', sa.VARCHAR(), nullable=True),
    sa.Column('reply_status_message', sa.VARCHAR(), nullable=True),
    sa.Column('review_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_review_hash'), 'review', ['review_hash'], unique=1)
    # ### end Alembic commands ###
