"""Add extra_person_price to RoomType

Revision ID: 42b9bd6b7d42
Revises: 20240209_rate_plan_enhancements
Create Date: 2026-02-09 17:46:04.366339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b9bd6b7d42'
down_revision: Union[str, Sequence[str], None] = '20240209_rate_plan_enhancements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_hotel_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_review_review_hash'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_pricing_rules_hotel_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.alter_column('integration_settings', 'widget_background_color',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'#FFFFFF'::character varying"))
    op.alter_column('rate_plans', 'min_los',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('rate_plans', 'advance_purchase_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rate_plans', 'inclusions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('rate_plans', 'dynamic_pricing_enabled')
    op.add_column('room_types', sa.Column('extra_person_price', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'extra_person_price')
    op.add_column('rate_plans', sa.Column('dynamic_pricing_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('rate_plans', 'inclusions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('rate_plans', 'advance_purchase_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rate_plans', 'min_los',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('integration_settings', 'widget_background_color',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'#FFFFFF'::character varying"))
    op.create_table('pricing_rules',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('min_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('pricing_rules_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_rules_pkey'))
    )
    op.create_index(op.f('ix_pricing_rules_hotel_id'), 'pricing_rules', ['hotel_id'], unique=False)
    op.create_table('review',
    sa.Column('guest_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('review_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_reply_draft', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_reply', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('review_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_status_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('review_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('review_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_pkey'))
    )
    op.create_index(op.f('ix_review_review_hash'), 'review', ['review_hash'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guest_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('GOOGLE', 'BOOKING', 'TRIPADVISOR', 'MANUAL', name='reviewsource'), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sentiment', postgresql.ENUM('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'PENDING', name='reviewsentiment'), autoincrement=False, nullable=False),
    sa.Column('ai_response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'DRAFTED', 'APPROVED', 'REPLIED', name='reviewstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('reviews_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('ix_reviews_hotel_id'), 'reviews', ['hotel_id'], unique=False)
    # ### end Alembic commands ###
