"""Make rate_plan_id nullable

Revision ID: bf18d7bcd56f
Revises: 42b9bd6b7d42
Create Date: 2026-02-09 18:06:53.089589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf18d7bcd56f'
down_revision: Union[str, Sequence[str], None] = '42b9bd6b7d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_rates', 'rate_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_rates', 'rate_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
