"""add_hotel_feature_flags

Revision ID: a0650c1ba586
Revises: 7e4a4c08e876
Create Date: 2026-02-10 14:39:11.186606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0650c1ba586'
down_revision: Union[str, Sequence[str], None] = '7e4a4c08e876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('feature_rate_shopper', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('hotels', sa.Column('feature_ai_agent', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('hotels', sa.Column('feature_guest_bot', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'feature_guest_bot')
    op.drop_column('hotels', 'feature_ai_agent')
    op.drop_column('hotels', 'feature_rate_shopper')
    # ### end Alembic commands ###
