"""add_ai_integration_keys

Revision ID: a0eaa83f98e2
Revises: 0fbe11b44b0f
Create Date: 2026-04-29 17:20:44.418110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0eaa83f98e2'
down_revision: Union[str, Sequence[str], None] = '0fbe11b44b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_settings', sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('integration_settings', sa.Column('ai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_settings', 'ai_api_key')
    op.drop_column('integration_settings', 'ai_provider')
    # ### end Alembic commands ###
