import React from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const DataDeletion = () => {
  return (
    <div className="min-h-screen bg-gray-50/50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <Link to="/" className="inline-flex items-center text-sm text-gray-500 hover:text-gray-900 mb-6">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>
        <Card className="border-0 shadow-xl bg-white/80 backdrop-blur-xl">
          <CardContent className="p-8 sm:p-12 prose prose-gray max-w-none">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 mb-8">User Data Deletion Instructions</h1>
            <p className="text-gray-500 mb-8">Last Updated: {new Date().toLocaleDateString()}</p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">How to request data deletion</h2>
              <p>
                In compliance with global privacy regulations (including GDPR and Meta's Platform Terms), you have the right to request 
                the complete deletion of your data from Staybooker's servers.
              </p>
              
              <div className="bg-blue-50 border-l-4 border-blue-500 p-6 my-6">
                <h3 className="text-xl font-semibold text-blue-900 mt-0">Deletion Process</h3>
                <p className="text-blue-800">
                  To request the deletion of your account and all associated data, please send an email to our technical support team at:
                </p>
                <p className="font-mono text-lg font-bold text-blue-900 my-4">
                  tech.revmerito@gmail.com
                </p>
                <p className="text-blue-800 mb-0">
                  Please use the subject line <strong>"Data Deletion Request"</strong> and include your registered email address or hotel name.
                </p>
              </div>
            </section>

            <section className="space-y-4 mt-8">
              <h2 className="text-2xl font-semibold text-gray-900">What data gets deleted?</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>Your personal account information (Name, Email, Password hashes).</li>
                <li>Your hotel's configuration and integration settings (Meta Tokens, Webhooks).</li>
                <li>Guest leads and chat history generated by the AI agent.</li>
              </ul>
            </section>

            <section className="space-y-4 mt-8">
              <h2 className="text-2xl font-semibold text-gray-900">Processing Time</h2>
              <p>
                We will process your data deletion request within 14 business days of receiving the email. 
                You will receive a confirmation reply once all your data has been permanently removed from our active databases.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default DataDeletion;
