import React from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";

const DataDeletion = () => {
  return (
    <div className="min-h-screen bg-background text-foreground py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <Link to="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>
        <Card className="border shadow-lg bg-card text-card-foreground overflow-hidden">
          {/* Brand Header */}
          <div className="bg-destructive/10 border-b p-8 sm:p-12 text-center">
            <Trash2 className="w-16 h-16 text-destructive mx-auto mb-4" />
            <h1 className="text-4xl font-extrabold tracking-tight text-destructive mb-2">User Data Deletion</h1>
            <p className="text-muted-foreground">Instructions for requesting data removal</p>
          </div>

          <CardContent className="p-8 sm:p-12 space-y-8 text-base leading-relaxed">
            <section className="space-y-4">
              <h2 className="text-2xl font-bold border-b pb-2">How to request data deletion</h2>
              <p>
                In compliance with global privacy regulations (including GDPR and Meta's Platform Terms), you have the right to request 
                the complete deletion of your data from Staybooker's servers.
              </p>
              
              <div className="bg-primary/5 border-l-4 border-primary p-6 my-6 rounded-r-lg">
                <h3 className="text-xl font-bold text-foreground mt-0 mb-2">Deletion Process</h3>
                <p className="text-muted-foreground">
                  To request the deletion of your account and all associated data, please send an email to our technical support team at:
                </p>
                <p className="font-mono text-xl font-extrabold text-primary my-4">
                  <a href="mailto:tech.revmerito@gmail.com" className="hover:underline">tech.revmerito@gmail.com</a>
                </p>
                <p className="text-muted-foreground mb-0">
                  Please use the subject line <strong className="text-foreground">"Data Deletion Request"</strong> and include your registered email address or hotel name.
                </p>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold border-b pb-2">What data gets deleted?</h2>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li><strong className="text-foreground">Account Info:</strong> Your personal account information (Name, Email, Password hashes).</li>
                <li><strong className="text-foreground">Integrations:</strong> Your hotel's configuration and integration settings (Meta Tokens, Webhooks).</li>
                <li><strong className="text-foreground">History:</strong> Guest leads and chat history generated by the AI agent.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold border-b pb-2">Processing Time</h2>
              <p>
                We will process your data deletion request within 14 business days of receiving the email. 
                You will receive a confirmation reply once all your data has been permanently removed from our active databases.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default DataDeletion;
