import { Wifi, Tv, Coffee, Snowflake, Waves, Dumbbell, Car, Utensils, Star, ShieldCheck, Sparkles, Wine, Bath, ShowerHead, BedDouble, Flame, Baby, Languages, ConciergeBell, WashingMachine, Key, Wind, CigaretteOff, PawPrint, VolumeX, Maximize, Briefcase, Map } from 'lucide-react';

export const ICONS: Record<string, any> = {
    wifi: Wifi,
    tv: Tv,
    coffee: Coffee,
    snowflake: Snowflake,
    waves: Waves,
    dumbbell: Dumbbell,
    car: Car,
    utensils: Utensils,
    star: Star,
    shield: ShieldCheck,
    sparkle: Sparkles,
    wine: Wine,
    bath: Bath,
    shower: ShowerHead,
    bed: BedDouble,
    flame: Flame,
    baby: Baby,
    globe: Languages,
    bell: ConciergeBell,
    laundry: WashingMachine,
    key: Key,
    wind: Wind,
    no_smoking: CigaretteOff,
    pet: PawPrint,
    volume_mute: VolumeX,
    expand: Maximize,
    briefcase: Briefcase,
    map: Map,
};
