from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
import matplotlib
matplotlib.use('Agg') # Non-interactive backend
import matplotlib.pyplot as plt
import io
from datetime import date

def generate_pdf_report(revenue: int, occupancy: int, period: str) -> str:
    """
    Generates a professional PDF report with charts for the given data.
    Returns the public URL to the generated PDF.
    """
    try:
        filename = f"report_{date.today().isoformat()}.pdf"
        
        # 1. Generate Chart (Matplotlib)
        plt.figure(figsize=(6, 4))
        categories = ['Room Revenue', 'F&B Revenue', 'Other']
        values = [revenue * 0.7, revenue * 0.2, revenue * 0.1] # Mock breakdown
        plt.bar(categories, values, color=['#3b82f6', '#10b981', '#f59e0b'])
        plt.title(f"Revenue Breakdown ({period})")
        plt.ylabel("Amount (INR)")
        
        chart_buffer = io.BytesIO()
        plt.savefig(chart_buffer, format='png', dpi=100)
        chart_buffer.seek(0)
        plt.close()
        
        chart_image = ImageReader(chart_buffer)
        
        # 2. Create PDF (ReportLab)
        pdf_buffer = io.BytesIO()
        c = canvas.Canvas(pdf_buffer, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "Staybooker Performance Report")
        
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 80, f"Generated on: {date.today().isoformat()}")
        c.drawString(50, height - 100, f"Period: {period}")
        
        # Stats Text
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 140, "Key Metrics:")
        
        c.setFont("Helvetica", 12)
        c.drawString(70, height - 160, f"Total Revenue: INR {revenue}")
        c.drawString(70, height - 180, f"Occupancy Rate: {occupancy}%")
        
        # Embed Chart using ImageReader (in-memory)
        c.drawImage(chart_image, 50, height - 450, width=500, height=300)
        
        # Footer
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, 50, "Generated by Staybooker AI Agent")
        
        c.save()
        pdf_content = pdf_buffer.getvalue()
        
        # 3. Upload to Supabase Storage
        try:
            from app.core.db.supabase import get_supabase
            supabase_client = get_supabase()
            
            supabase_client.storage.from_("reports").upload(
                path=filename,
                file=pdf_content,
                file_options={"content-type": "application/pdf"}
            )
            
            # Get Public URL
            url_res = supabase_client.storage.from_("reports").get_public_url(filename)
            
            return url_res
            
        except Exception as upload_err:
             return f"Report generated but upload to Supabase failed: {str(upload_err)}"

    except Exception as e:
        return f"Report generation failed: {str(e)}"
